[package]
name = "lyng-builtins"
version.workspace = true
edition.workspace = true

[dependencies]
lyng-common = { workspace = true }
lyng-types = { workspace = true }
lyng-gc = { workspace = true }
lyng-ops = { workspace = true }
lyng-objects = { workspace = true }
lyng-env = { workspace = true }
lyng-host = { workspace = true }
lyng-parser = { workspace = true }
