[package]
name = "lyng-tests"
version.workspace = true
edition.workspace = true

[dependencies]
lyng-common = { workspace = true }
lyng-lexer = { workspace = true }
lyng-ast = { workspace = true }
lyng-parser = { workspace = true }
lyng-sema = { workspace = true }
lyng-types = { workspace = true }
lyng-gc = { workspace = true }
lyng-ops = { workspace = true }
lyng-host = { workspace = true }
lyng-objects = { workspace = true }
lyng-env = { workspace = true }
lyng-bytecode = { workspace = true }
lyng-compiler = { workspace = true }
lyng-vm = { workspace = true }
lyng-builtins = { workspace = true }

[lints]
workspace = true
