//! DSL handler functions per design §10 (DSL-0b).
//!
//! Each opcode's asm-DSL handler is a `#[unsafe(naked)] extern "C" fn`
//! that the trampoline tail-jumps to via the dispatch table. The
//! actual handler bodies are emitted by the `lyng_js_vm_dsl::llint_handler!`
//! proc-macro across three "temperature" families:
//!
//! - [`hot`]   — populated by B39–B42 (hottest opcodes: SMI arith, register
//!   moves, fast-path object access).
//! - [`warm`]  — populated by B43–B45 (mid-frequency opcodes: branches,
//!   property loads/stores, prefix opcodes).
//! - [`cold`]  — auto-generated by B46–B47 (every remaining opcode lowered
//!   to a `call_slow!`-only cold stub).
//!
//! For DSL-0b Batch 4 the table itself is still a placeholder —
//! every slot points to `unimplemented_dsl_handler`. The real
//! population happens in B47 (after cold stubs land), at which point
//! `DSL_DISPATCH_TABLE` is rebuilt from the `OPCODES` manifest and
//! the per-family handler symbols.

pub mod cold;
pub mod hot;
pub mod warm;

/// Calling convention for a DSL handler. The asm trampoline tail-calls
/// these via the dispatch table indexed by opcode byte; handlers never
/// return — they either tail-jump to the next handler or branch to
/// `_interpreter_exit`.
pub type DslHandler = unsafe extern "C" fn() -> !;

/// Placeholder dispatch table; finalized in B47 once cold stubs land.
#[allow(dead_code)]
pub static DSL_DISPATCH_TABLE: [DslHandler; 256] = [unimplemented_dsl_handler; 256];

/// Diverging placeholder used until B47 emits the real table. Hit
/// only if the trampoline is somehow re-entered before DSL-0c flips
/// dispatch — currently unreachable since the trampoline is itself a
/// stub.
#[allow(dead_code)]
unsafe extern "C" fn unimplemented_dsl_handler() -> ! {
    loop {} // SAFETY: never reachable until DSL-0c flips dispatch.
}
