use super::super::{
    install_public_builtin_function, install_public_ordinary_object, BinaryDataFamilyBuiltins,
    BinaryDataFamilyPrototypes, FamilyInstallContext,
};
use lyng_js_env::Agent;
use lyng_js_types::{
    array_buffer_builtin, array_buffer_byte_length_getter_builtin, array_buffer_is_view_builtin,
    array_buffer_resize_builtin, array_buffer_slice_builtin, atomics_add_builtin,
    atomics_and_builtin, atomics_compare_exchange_builtin, atomics_exchange_builtin,
    atomics_is_lock_free_builtin, atomics_load_builtin, atomics_notify_builtin, atomics_or_builtin,
    atomics_pause_builtin, atomics_store_builtin, atomics_sub_builtin, atomics_wait_async_builtin,
    atomics_wait_builtin, atomics_xor_builtin, big_int64_array_builtin, big_uint64_array_builtin,
    data_view_buffer_getter_builtin, data_view_builtin, data_view_byte_length_getter_builtin,
    data_view_byte_offset_getter_builtin, data_view_get_big_int64_builtin,
    data_view_get_big_uint64_builtin, data_view_get_float16_builtin, data_view_get_float32_builtin,
    data_view_get_float64_builtin, data_view_get_int16_builtin, data_view_get_int32_builtin,
    data_view_get_int8_builtin, data_view_get_uint16_builtin, data_view_get_uint32_builtin,
    data_view_get_uint8_builtin, data_view_set_big_int64_builtin, data_view_set_big_uint64_builtin,
    data_view_set_float16_builtin, data_view_set_float32_builtin, data_view_set_float64_builtin,
    data_view_set_int16_builtin, data_view_set_int32_builtin, data_view_set_int8_builtin,
    data_view_set_uint16_builtin, data_view_set_uint32_builtin, data_view_set_uint8_builtin,
    float32_array_builtin, float64_array_builtin, int16_array_builtin, int32_array_builtin,
    int8_array_builtin, shared_array_buffer_builtin,
    shared_array_buffer_byte_length_getter_builtin, shared_array_buffer_slice_builtin,
    typed_array_at_builtin, typed_array_builtin, typed_array_copy_within_builtin,
    typed_array_every_builtin, typed_array_fill_builtin, typed_array_filter_builtin,
    typed_array_find_builtin, typed_array_find_index_builtin, typed_array_find_last_builtin,
    typed_array_find_last_index_builtin, typed_array_for_each_builtin, typed_array_from_builtin,
    typed_array_includes_builtin, typed_array_index_of_builtin, typed_array_join_builtin,
    typed_array_last_index_of_builtin, typed_array_map_builtin, typed_array_of_builtin,
    typed_array_reduce_builtin, typed_array_reduce_right_builtin, typed_array_reverse_builtin,
    typed_array_some_builtin, typed_array_sort_builtin, typed_array_to_locale_string_builtin,
    typed_array_to_reversed_builtin, typed_array_to_sorted_builtin, typed_array_to_string_builtin,
    typed_array_to_string_tag_getter_builtin, typed_array_with_builtin, uint16_array_builtin,
    uint32_array_builtin, uint8_array_buffer_getter_builtin, uint8_array_builtin,
    uint8_array_byte_length_getter_builtin, uint8_array_byte_offset_getter_builtin,
    uint8_array_entries_builtin, uint8_array_from_base64_builtin, uint8_array_from_hex_builtin,
    uint8_array_keys_builtin, uint8_array_length_getter_builtin, uint8_array_set_builtin,
    uint8_array_set_from_base64_builtin, uint8_array_set_from_hex_builtin,
    uint8_array_slice_builtin, uint8_array_subarray_builtin, uint8_array_to_base64_builtin,
    uint8_array_to_hex_builtin, uint8_array_values_builtin, uint8_clamped_array_builtin,
    BuiltinFunctionId, ObjectRef,
};

#[allow(clippy::too_many_lines)]
pub(in crate::public) fn install_binary_data_family(
    agent: &mut Agent,
    cx: FamilyInstallContext,
    prototypes: BinaryDataFamilyPrototypes,
) -> BinaryDataFamilyBuiltins {
    let constructors = install_binary_data_constructors(agent, cx, prototypes);
    let buffer_methods = install_buffer_methods(agent, cx);
    let atomics_methods = install_atomics_methods(agent, cx);
    let data_view_methods = install_data_view_methods(agent, cx);
    let typed_array_methods = install_typed_array_methods(agent, cx);

    BinaryDataFamilyBuiltins {
        array_buffer: constructors.array_buffer,
        shared_array_buffer: constructors.shared_array_buffer,
        atomics: constructors.atomics,
        array_buffer_is_view: constructors.array_buffer_is_view,
        data_view: constructors.data_view,
        typed_array: constructors.typed_array,
        typed_array_from: constructors.typed_array_from,
        typed_array_of: constructors.typed_array_of,
        int8_array: constructors.int8_array,
        int16_array: constructors.int16_array,
        int32_array: constructors.int32_array,
        float32_array: constructors.float32_array,
        float64_array: constructors.float64_array,
        big_int64_array: constructors.big_int64_array,
        big_uint64_array: constructors.big_uint64_array,
        uint32_array: constructors.uint32_array,
        uint16_array: constructors.uint16_array,
        uint8_clamped_array: constructors.uint8_clamped_array,
        uint8_array: constructors.uint8_array,
        array_buffer_prototype: prototypes.array_buffer_prototype,
        shared_array_buffer_prototype: prototypes.shared_array_buffer_prototype,
        array_buffer_byte_length_getter: buffer_methods.array_buffer_byte_length_getter,
        array_buffer_resize: buffer_methods.array_buffer_resize,
        array_buffer_slice: buffer_methods.array_buffer_slice,
        shared_array_buffer_byte_length_getter: buffer_methods
            .shared_array_buffer_byte_length_getter,
        shared_array_buffer_slice: buffer_methods.shared_array_buffer_slice,
        atomics_load: atomics_methods.load,
        atomics_store: atomics_methods.store,
        atomics_add: atomics_methods.add,
        atomics_sub: atomics_methods.sub,
        atomics_and: atomics_methods.and,
        atomics_or: atomics_methods.or,
        atomics_xor: atomics_methods.xor,
        atomics_exchange: atomics_methods.exchange,
        atomics_compare_exchange: atomics_methods.compare_exchange,
        atomics_notify: atomics_methods.notify,
        atomics_wait: atomics_methods.wait,
        atomics_wait_async: atomics_methods.wait_async,
        atomics_pause: atomics_methods.pause,
        atomics_is_lock_free: atomics_methods.is_lock_free,
        data_view_prototype: prototypes.data_view_prototype,
        data_view_buffer_getter: data_view_methods.buffer_getter,
        data_view_byte_length_getter: data_view_methods.byte_length_getter,
        data_view_byte_offset_getter: data_view_methods.byte_offset_getter,
        data_view_get_float32: data_view_methods.get_float32,
        data_view_get_float64: data_view_methods.get_float64,
        data_view_get_int16: data_view_methods.get_int16,
        data_view_get_int32: data_view_methods.get_int32,
        data_view_get_int8: data_view_methods.get_int8,
        data_view_get_uint16: data_view_methods.get_uint16,
        data_view_get_uint32: data_view_methods.get_uint32,
        data_view_get_uint8: data_view_methods.get_uint8,
        data_view_set_float32: data_view_methods.set_float32,
        data_view_set_float64: data_view_methods.set_float64,
        data_view_set_int16: data_view_methods.set_int16,
        data_view_set_int32: data_view_methods.set_int32,
        data_view_set_int8: data_view_methods.set_int8,
        data_view_set_uint16: data_view_methods.set_uint16,
        data_view_set_uint32: data_view_methods.set_uint32,
        data_view_set_uint8: data_view_methods.set_uint8,
        data_view_get_big_int64: data_view_methods.get_big_int64,
        data_view_get_big_uint64: data_view_methods.get_big_uint64,
        data_view_set_big_int64: data_view_methods.set_big_int64,
        data_view_set_big_uint64: data_view_methods.set_big_uint64,
        data_view_get_float16: data_view_methods.get_float16,
        data_view_set_float16: data_view_methods.set_float16,
        typed_array_prototype: prototypes.typed_array_prototype,
        int8_array_prototype: prototypes.int8_array_prototype,
        int16_array_prototype: prototypes.int16_array_prototype,
        int32_array_prototype: prototypes.int32_array_prototype,
        float32_array_prototype: prototypes.float32_array_prototype,
        float64_array_prototype: prototypes.float64_array_prototype,
        big_int64_array_prototype: prototypes.big_int64_array_prototype,
        big_uint64_array_prototype: prototypes.big_uint64_array_prototype,
        uint32_array_prototype: prototypes.uint32_array_prototype,
        uint16_array_prototype: prototypes.uint16_array_prototype,
        uint8_clamped_array_prototype: prototypes.uint8_clamped_array_prototype,
        uint8_array_prototype: prototypes.uint8_array_prototype,
        uint8_array_buffer_getter: typed_array_methods.buffer_getter,
        uint8_array_byte_length_getter: typed_array_methods.byte_length_getter,
        uint8_array_byte_offset_getter: typed_array_methods.byte_offset_getter,
        uint8_array_length_getter: typed_array_methods.length_getter,
        uint8_array_values: typed_array_methods.values,
        uint8_array_keys: typed_array_methods.keys,
        uint8_array_entries: typed_array_methods.entries,
        uint8_array_set: typed_array_methods.set,
        uint8_array_slice: typed_array_methods.slice,
        uint8_array_subarray: typed_array_methods.subarray,
        uint8_array_from_base64: typed_array_methods.from_base64,
        uint8_array_from_hex: typed_array_methods.from_hex,
        uint8_array_set_from_base64: typed_array_methods.set_from_base64,
        uint8_array_set_from_hex: typed_array_methods.set_from_hex,
        uint8_array_to_base64: typed_array_methods.to_base64,
        uint8_array_to_hex: typed_array_methods.to_hex,
        typed_array_every: typed_array_methods.every,
        typed_array_some: typed_array_methods.some,
        typed_array_find: typed_array_methods.find,
        typed_array_find_index: typed_array_methods.find_index,
        typed_array_find_last: typed_array_methods.find_last,
        typed_array_find_last_index: typed_array_methods.find_last_index,
        typed_array_fill: typed_array_methods.fill,
        typed_array_copy_within: typed_array_methods.copy_within,
        typed_array_filter: typed_array_methods.filter,
        typed_array_for_each: typed_array_methods.for_each,
        typed_array_includes: typed_array_methods.includes,
        typed_array_index_of: typed_array_methods.index_of,
        typed_array_join: typed_array_methods.join,
        typed_array_last_index_of: typed_array_methods.last_index_of,
        typed_array_map: typed_array_methods.map,
        typed_array_reduce: typed_array_methods.reduce,
        typed_array_reduce_right: typed_array_methods.reduce_right,
        typed_array_reverse: typed_array_methods.reverse,
        typed_array_sort: typed_array_methods.sort,
        typed_array_to_locale_string: typed_array_methods.to_locale_string,
        typed_array_to_string: typed_array_methods.to_string,
        typed_array_to_reversed: typed_array_methods.to_reversed,
        typed_array_to_sorted: typed_array_methods.to_sorted,
        typed_array_with: typed_array_methods.with,
        typed_array_at: typed_array_methods.at,
        typed_array_to_string_tag_getter: typed_array_methods.to_string_tag_getter,
    }
}

#[derive(Clone, Copy, Debug)]
struct BinaryDataConstructorBuiltins {
    array_buffer: ObjectRef,
    shared_array_buffer: ObjectRef,
    atomics: ObjectRef,
    array_buffer_is_view: ObjectRef,
    data_view: ObjectRef,
    typed_array: ObjectRef,
    typed_array_from: ObjectRef,
    typed_array_of: ObjectRef,
    int8_array: ObjectRef,
    int16_array: ObjectRef,
    int32_array: ObjectRef,
    float32_array: ObjectRef,
    float64_array: ObjectRef,
    big_int64_array: ObjectRef,
    big_uint64_array: ObjectRef,
    uint32_array: ObjectRef,
    uint16_array: ObjectRef,
    uint8_clamped_array: ObjectRef,
    uint8_array: ObjectRef,
}

fn install_binary_data_constructors(
    agent: &mut Agent,
    cx: FamilyInstallContext,
    prototypes: BinaryDataFamilyPrototypes,
) -> BinaryDataConstructorBuiltins {
    BinaryDataConstructorBuiltins {
        array_buffer: install_with_prototype(
            agent,
            cx,
            array_buffer_builtin(),
            prototypes.array_buffer_prototype,
        ),
        shared_array_buffer: install_with_prototype(
            agent,
            cx,
            shared_array_buffer_builtin(),
            prototypes.shared_array_buffer_prototype,
        ),
        atomics: install_public_ordinary_object(agent, cx, Some(cx.object_prototype)),
        array_buffer_is_view: install(agent, cx, array_buffer_is_view_builtin()),
        data_view: install_with_prototype(
            agent,
            cx,
            data_view_builtin(),
            prototypes.data_view_prototype,
        ),
        typed_array: install_with_prototype(
            agent,
            cx,
            typed_array_builtin(),
            prototypes.typed_array_prototype,
        ),
        typed_array_from: install(agent, cx, typed_array_from_builtin()),
        typed_array_of: install(agent, cx, typed_array_of_builtin()),
        int8_array: install_with_prototype(
            agent,
            cx,
            int8_array_builtin(),
            prototypes.int8_array_prototype,
        ),
        int16_array: install_with_prototype(
            agent,
            cx,
            int16_array_builtin(),
            prototypes.int16_array_prototype,
        ),
        int32_array: install_with_prototype(
            agent,
            cx,
            int32_array_builtin(),
            prototypes.int32_array_prototype,
        ),
        float32_array: install_with_prototype(
            agent,
            cx,
            float32_array_builtin(),
            prototypes.float32_array_prototype,
        ),
        float64_array: install_with_prototype(
            agent,
            cx,
            float64_array_builtin(),
            prototypes.float64_array_prototype,
        ),
        big_int64_array: install_with_prototype(
            agent,
            cx,
            big_int64_array_builtin(),
            prototypes.big_int64_array_prototype,
        ),
        big_uint64_array: install_with_prototype(
            agent,
            cx,
            big_uint64_array_builtin(),
            prototypes.big_uint64_array_prototype,
        ),
        uint32_array: install_with_prototype(
            agent,
            cx,
            uint32_array_builtin(),
            prototypes.uint32_array_prototype,
        ),
        uint16_array: install_with_prototype(
            agent,
            cx,
            uint16_array_builtin(),
            prototypes.uint16_array_prototype,
        ),
        uint8_clamped_array: install_with_prototype(
            agent,
            cx,
            uint8_clamped_array_builtin(),
            prototypes.uint8_clamped_array_prototype,
        ),
        uint8_array: install_with_prototype(
            agent,
            cx,
            uint8_array_builtin(),
            prototypes.uint8_array_prototype,
        ),
    }
}

#[derive(Clone, Copy, Debug)]
struct BufferMethodBuiltins {
    array_buffer_byte_length_getter: ObjectRef,
    array_buffer_resize: ObjectRef,
    array_buffer_slice: ObjectRef,
    shared_array_buffer_byte_length_getter: ObjectRef,
    shared_array_buffer_slice: ObjectRef,
}

fn install_buffer_methods(agent: &mut Agent, cx: FamilyInstallContext) -> BufferMethodBuiltins {
    BufferMethodBuiltins {
        array_buffer_byte_length_getter: install(
            agent,
            cx,
            array_buffer_byte_length_getter_builtin(),
        ),
        array_buffer_resize: install(agent, cx, array_buffer_resize_builtin()),
        array_buffer_slice: install(agent, cx, array_buffer_slice_builtin()),
        shared_array_buffer_byte_length_getter: install(
            agent,
            cx,
            shared_array_buffer_byte_length_getter_builtin(),
        ),
        shared_array_buffer_slice: install(agent, cx, shared_array_buffer_slice_builtin()),
    }
}

#[derive(Clone, Copy, Debug)]
struct AtomicsMethodBuiltins {
    load: ObjectRef,
    store: ObjectRef,
    add: ObjectRef,
    sub: ObjectRef,
    and: ObjectRef,
    or: ObjectRef,
    xor: ObjectRef,
    exchange: ObjectRef,
    compare_exchange: ObjectRef,
    notify: ObjectRef,
    wait: ObjectRef,
    wait_async: ObjectRef,
    pause: ObjectRef,
    is_lock_free: ObjectRef,
}

fn install_atomics_methods(agent: &mut Agent, cx: FamilyInstallContext) -> AtomicsMethodBuiltins {
    AtomicsMethodBuiltins {
        load: install(agent, cx, atomics_load_builtin()),
        store: install(agent, cx, atomics_store_builtin()),
        add: install(agent, cx, atomics_add_builtin()),
        sub: install(agent, cx, atomics_sub_builtin()),
        and: install(agent, cx, atomics_and_builtin()),
        or: install(agent, cx, atomics_or_builtin()),
        xor: install(agent, cx, atomics_xor_builtin()),
        exchange: install(agent, cx, atomics_exchange_builtin()),
        compare_exchange: install(agent, cx, atomics_compare_exchange_builtin()),
        notify: install(agent, cx, atomics_notify_builtin()),
        wait: install(agent, cx, atomics_wait_builtin()),
        wait_async: install(agent, cx, atomics_wait_async_builtin()),
        pause: install(agent, cx, atomics_pause_builtin()),
        is_lock_free: install(agent, cx, atomics_is_lock_free_builtin()),
    }
}

#[derive(Clone, Copy, Debug)]
struct DataViewMethodBuiltins {
    buffer_getter: ObjectRef,
    byte_length_getter: ObjectRef,
    byte_offset_getter: ObjectRef,
    get_float32: ObjectRef,
    get_float64: ObjectRef,
    get_int16: ObjectRef,
    get_int32: ObjectRef,
    get_int8: ObjectRef,
    get_uint16: ObjectRef,
    get_uint32: ObjectRef,
    get_uint8: ObjectRef,
    set_float32: ObjectRef,
    set_float64: ObjectRef,
    set_int16: ObjectRef,
    set_int32: ObjectRef,
    set_int8: ObjectRef,
    set_uint16: ObjectRef,
    set_uint32: ObjectRef,
    set_uint8: ObjectRef,
    get_big_int64: ObjectRef,
    get_big_uint64: ObjectRef,
    set_big_int64: ObjectRef,
    set_big_uint64: ObjectRef,
    get_float16: ObjectRef,
    set_float16: ObjectRef,
}

fn install_data_view_methods(
    agent: &mut Agent,
    cx: FamilyInstallContext,
) -> DataViewMethodBuiltins {
    DataViewMethodBuiltins {
        buffer_getter: install(agent, cx, data_view_buffer_getter_builtin()),
        byte_length_getter: install(agent, cx, data_view_byte_length_getter_builtin()),
        byte_offset_getter: install(agent, cx, data_view_byte_offset_getter_builtin()),
        get_float32: install(agent, cx, data_view_get_float32_builtin()),
        get_float64: install(agent, cx, data_view_get_float64_builtin()),
        get_int16: install(agent, cx, data_view_get_int16_builtin()),
        get_int32: install(agent, cx, data_view_get_int32_builtin()),
        get_int8: install(agent, cx, data_view_get_int8_builtin()),
        get_uint16: install(agent, cx, data_view_get_uint16_builtin()),
        get_uint32: install(agent, cx, data_view_get_uint32_builtin()),
        get_uint8: install(agent, cx, data_view_get_uint8_builtin()),
        set_float32: install(agent, cx, data_view_set_float32_builtin()),
        set_float64: install(agent, cx, data_view_set_float64_builtin()),
        set_int16: install(agent, cx, data_view_set_int16_builtin()),
        set_int32: install(agent, cx, data_view_set_int32_builtin()),
        set_int8: install(agent, cx, data_view_set_int8_builtin()),
        set_uint16: install(agent, cx, data_view_set_uint16_builtin()),
        set_uint32: install(agent, cx, data_view_set_uint32_builtin()),
        set_uint8: install(agent, cx, data_view_set_uint8_builtin()),
        get_big_int64: install(agent, cx, data_view_get_big_int64_builtin()),
        get_big_uint64: install(agent, cx, data_view_get_big_uint64_builtin()),
        set_big_int64: install(agent, cx, data_view_set_big_int64_builtin()),
        set_big_uint64: install(agent, cx, data_view_set_big_uint64_builtin()),
        get_float16: install(agent, cx, data_view_get_float16_builtin()),
        set_float16: install(agent, cx, data_view_set_float16_builtin()),
    }
}

#[derive(Clone, Copy, Debug)]
struct TypedArrayMethodBuiltins {
    buffer_getter: ObjectRef,
    byte_length_getter: ObjectRef,
    byte_offset_getter: ObjectRef,
    length_getter: ObjectRef,
    values: ObjectRef,
    keys: ObjectRef,
    entries: ObjectRef,
    set: ObjectRef,
    slice: ObjectRef,
    subarray: ObjectRef,
    from_base64: ObjectRef,
    from_hex: ObjectRef,
    set_from_base64: ObjectRef,
    set_from_hex: ObjectRef,
    to_base64: ObjectRef,
    to_hex: ObjectRef,
    every: ObjectRef,
    some: ObjectRef,
    find: ObjectRef,
    find_index: ObjectRef,
    find_last: ObjectRef,
    find_last_index: ObjectRef,
    fill: ObjectRef,
    copy_within: ObjectRef,
    filter: ObjectRef,
    for_each: ObjectRef,
    includes: ObjectRef,
    index_of: ObjectRef,
    join: ObjectRef,
    last_index_of: ObjectRef,
    map: ObjectRef,
    reduce: ObjectRef,
    reduce_right: ObjectRef,
    reverse: ObjectRef,
    sort: ObjectRef,
    to_locale_string: ObjectRef,
    to_string: ObjectRef,
    to_reversed: ObjectRef,
    to_sorted: ObjectRef,
    with: ObjectRef,
    at: ObjectRef,
    to_string_tag_getter: ObjectRef,
}

#[allow(clippy::too_many_lines)]
fn install_typed_array_methods(
    agent: &mut Agent,
    cx: FamilyInstallContext,
) -> TypedArrayMethodBuiltins {
    TypedArrayMethodBuiltins {
        buffer_getter: install(agent, cx, uint8_array_buffer_getter_builtin()),
        byte_length_getter: install(agent, cx, uint8_array_byte_length_getter_builtin()),
        byte_offset_getter: install(agent, cx, uint8_array_byte_offset_getter_builtin()),
        length_getter: install(agent, cx, uint8_array_length_getter_builtin()),
        values: install(agent, cx, uint8_array_values_builtin()),
        keys: install(agent, cx, uint8_array_keys_builtin()),
        entries: install(agent, cx, uint8_array_entries_builtin()),
        set: install(agent, cx, uint8_array_set_builtin()),
        slice: install(agent, cx, uint8_array_slice_builtin()),
        subarray: install(agent, cx, uint8_array_subarray_builtin()),
        from_base64: install(agent, cx, uint8_array_from_base64_builtin()),
        from_hex: install(agent, cx, uint8_array_from_hex_builtin()),
        set_from_base64: install(agent, cx, uint8_array_set_from_base64_builtin()),
        set_from_hex: install(agent, cx, uint8_array_set_from_hex_builtin()),
        to_base64: install(agent, cx, uint8_array_to_base64_builtin()),
        to_hex: install(agent, cx, uint8_array_to_hex_builtin()),
        every: install(agent, cx, typed_array_every_builtin()),
        some: install(agent, cx, typed_array_some_builtin()),
        find: install(agent, cx, typed_array_find_builtin()),
        find_index: install(agent, cx, typed_array_find_index_builtin()),
        find_last: install(agent, cx, typed_array_find_last_builtin()),
        find_last_index: install(agent, cx, typed_array_find_last_index_builtin()),
        fill: install(agent, cx, typed_array_fill_builtin()),
        copy_within: install(agent, cx, typed_array_copy_within_builtin()),
        filter: install(agent, cx, typed_array_filter_builtin()),
        for_each: install(agent, cx, typed_array_for_each_builtin()),
        includes: install(agent, cx, typed_array_includes_builtin()),
        index_of: install(agent, cx, typed_array_index_of_builtin()),
        join: install(agent, cx, typed_array_join_builtin()),
        last_index_of: install(agent, cx, typed_array_last_index_of_builtin()),
        map: install(agent, cx, typed_array_map_builtin()),
        reduce: install(agent, cx, typed_array_reduce_builtin()),
        reduce_right: install(agent, cx, typed_array_reduce_right_builtin()),
        reverse: install(agent, cx, typed_array_reverse_builtin()),
        sort: install(agent, cx, typed_array_sort_builtin()),
        to_locale_string: install(agent, cx, typed_array_to_locale_string_builtin()),
        to_string: install(agent, cx, typed_array_to_string_builtin()),
        to_reversed: install(agent, cx, typed_array_to_reversed_builtin()),
        to_sorted: install(agent, cx, typed_array_to_sorted_builtin()),
        with: install(agent, cx, typed_array_with_builtin()),
        at: install(agent, cx, typed_array_at_builtin()),
        to_string_tag_getter: install(agent, cx, typed_array_to_string_tag_getter_builtin()),
    }
}

fn install(agent: &mut Agent, cx: FamilyInstallContext, entry: BuiltinFunctionId) -> ObjectRef {
    install_public_builtin_function(agent, cx, entry, None)
}

fn install_with_prototype(
    agent: &mut Agent,
    cx: FamilyInstallContext,
    entry: BuiltinFunctionId,
    prototype: ObjectRef,
) -> ObjectRef {
    install_public_builtin_function(agent, cx, entry, Some(prototype))
}
