use super::{
    install_public_builtin_function, CollectionFamilyBuiltins, CollectionFamilyPrototypes,
    FamilyInstallContext,
};
use lyng_js_env::Agent;
use lyng_js_types::{
    js3_finalization_registry_builtin, js3_finalization_registry_register_builtin,
    js3_finalization_registry_unregister_builtin, js3_map_builtin, js3_map_clear_builtin,
    js3_map_delete_builtin, js3_map_entries_builtin, js3_map_for_each_builtin, js3_map_get_builtin,
    js3_map_has_builtin, js3_map_keys_builtin, js3_map_set_builtin, js3_map_size_getter_builtin,
    js3_map_values_builtin, js3_set_add_builtin, js3_set_builtin, js3_set_clear_builtin,
    js3_set_delete_builtin, js3_set_entries_builtin, js3_set_for_each_builtin, js3_set_has_builtin,
    js3_set_keys_builtin, js3_set_size_getter_builtin, js3_set_values_builtin,
    js3_weak_map_builtin, js3_weak_map_delete_builtin, js3_weak_map_get_builtin,
    js3_weak_map_has_builtin, js3_weak_map_set_builtin, js3_weak_ref_builtin,
    js3_weak_ref_deref_builtin, js3_weak_set_add_builtin, js3_weak_set_builtin,
    js3_weak_set_delete_builtin, js3_weak_set_has_builtin,
};

#[allow(clippy::too_many_lines)]
pub(in crate::public) fn install_collection_family(
    agent: &mut Agent,
    cx: FamilyInstallContext,
    prototypes: CollectionFamilyPrototypes,
) -> CollectionFamilyBuiltins {
    CollectionFamilyBuiltins {
        map: install_public_builtin_function(
            agent,
            cx,
            js3_map_builtin(),
            Some(prototypes.map_prototype),
        ),
        set: install_public_builtin_function(
            agent,
            cx,
            js3_set_builtin(),
            Some(prototypes.set_prototype),
        ),
        weak_map: install_public_builtin_function(
            agent,
            cx,
            js3_weak_map_builtin(),
            Some(prototypes.weak_map_prototype),
        ),
        weak_set: install_public_builtin_function(
            agent,
            cx,
            js3_weak_set_builtin(),
            Some(prototypes.weak_set_prototype),
        ),
        weak_ref: install_public_builtin_function(
            agent,
            cx,
            js3_weak_ref_builtin(),
            Some(prototypes.weak_ref_prototype),
        ),
        finalization_registry: install_public_builtin_function(
            agent,
            cx,
            js3_finalization_registry_builtin(),
            Some(prototypes.finalization_registry_prototype),
        ),
        map_get: install_public_builtin_function(agent, cx, js3_map_get_builtin(), None),
        map_set: install_public_builtin_function(agent, cx, js3_map_set_builtin(), None),
        map_has: install_public_builtin_function(agent, cx, js3_map_has_builtin(), None),
        map_delete: install_public_builtin_function(agent, cx, js3_map_delete_builtin(), None),
        map_clear: install_public_builtin_function(agent, cx, js3_map_clear_builtin(), None),
        map_entries: install_public_builtin_function(agent, cx, js3_map_entries_builtin(), None),
        map_values: install_public_builtin_function(agent, cx, js3_map_values_builtin(), None),
        map_keys: install_public_builtin_function(agent, cx, js3_map_keys_builtin(), None),
        map_for_each: install_public_builtin_function(agent, cx, js3_map_for_each_builtin(), None),
        map_size_getter: install_public_builtin_function(
            agent,
            cx,
            js3_map_size_getter_builtin(),
            None,
        ),
        set_add: install_public_builtin_function(agent, cx, js3_set_add_builtin(), None),
        set_has: install_public_builtin_function(agent, cx, js3_set_has_builtin(), None),
        set_delete: install_public_builtin_function(agent, cx, js3_set_delete_builtin(), None),
        set_clear: install_public_builtin_function(agent, cx, js3_set_clear_builtin(), None),
        set_entries: install_public_builtin_function(agent, cx, js3_set_entries_builtin(), None),
        set_values: install_public_builtin_function(agent, cx, js3_set_values_builtin(), None),
        set_keys: install_public_builtin_function(agent, cx, js3_set_keys_builtin(), None),
        set_for_each: install_public_builtin_function(agent, cx, js3_set_for_each_builtin(), None),
        set_size_getter: install_public_builtin_function(
            agent,
            cx,
            js3_set_size_getter_builtin(),
            None,
        ),
        weak_map_get: install_public_builtin_function(agent, cx, js3_weak_map_get_builtin(), None),
        weak_map_set: install_public_builtin_function(agent, cx, js3_weak_map_set_builtin(), None),
        weak_map_has: install_public_builtin_function(agent, cx, js3_weak_map_has_builtin(), None),
        weak_map_delete: install_public_builtin_function(
            agent,
            cx,
            js3_weak_map_delete_builtin(),
            None,
        ),
        weak_set_add: install_public_builtin_function(agent, cx, js3_weak_set_add_builtin(), None),
        weak_set_has: install_public_builtin_function(agent, cx, js3_weak_set_has_builtin(), None),
        weak_set_delete: install_public_builtin_function(
            agent,
            cx,
            js3_weak_set_delete_builtin(),
            None,
        ),
        weak_ref_deref: install_public_builtin_function(
            agent,
            cx,
            js3_weak_ref_deref_builtin(),
            None,
        ),
        finalization_registry_register: install_public_builtin_function(
            agent,
            cx,
            js3_finalization_registry_register_builtin(),
            None,
        ),
        finalization_registry_unregister: install_public_builtin_function(
            agent,
            cx,
            js3_finalization_registry_unregister_builtin(),
            None,
        ),
        map_prototype: prototypes.map_prototype,
        set_prototype: prototypes.set_prototype,
        weak_map_prototype: prototypes.weak_map_prototype,
        weak_set_prototype: prototypes.weak_set_prototype,
        weak_ref_prototype: prototypes.weak_ref_prototype,
        finalization_registry_prototype: prototypes.finalization_registry_prototype,
    }
}
