use super::{CollectionFamilyBuiltins, CollectionFamilyPrototypes, FamilyInstallContext};
use crate::public::{allocate_builtin_function_object, public_builtin_metadata};
use lyng_js_env::Agent;
use lyng_js_types::{
    js3_finalization_registry_builtin, js3_finalization_registry_register_builtin,
    js3_finalization_registry_unregister_builtin, js3_map_builtin, js3_map_clear_builtin,
    js3_map_delete_builtin, js3_map_entries_builtin, js3_map_for_each_builtin, js3_map_get_builtin,
    js3_map_has_builtin, js3_map_keys_builtin, js3_map_set_builtin, js3_map_size_getter_builtin,
    js3_map_values_builtin, js3_set_add_builtin, js3_set_builtin, js3_set_clear_builtin,
    js3_set_delete_builtin, js3_set_entries_builtin, js3_set_for_each_builtin, js3_set_has_builtin,
    js3_set_keys_builtin, js3_set_size_getter_builtin, js3_set_values_builtin,
    js3_weak_map_builtin, js3_weak_map_delete_builtin, js3_weak_map_get_builtin,
    js3_weak_map_has_builtin, js3_weak_map_set_builtin, js3_weak_ref_builtin,
    js3_weak_ref_deref_builtin, js3_weak_set_add_builtin, js3_weak_set_builtin,
    js3_weak_set_delete_builtin, js3_weak_set_has_builtin,
};

#[allow(clippy::too_many_lines)]
pub(in crate::public) fn install_collection_family(
    agent: &mut Agent,
    cx: FamilyInstallContext,
    prototypes: CollectionFamilyPrototypes,
) -> CollectionFamilyBuiltins {
    CollectionFamilyBuiltins {
        map: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_map_builtin(),
            public_builtin_metadata(js3_map_builtin()).unwrap(),
            Some(prototypes.map_prototype),
        ),
        set: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_set_builtin(),
            public_builtin_metadata(js3_set_builtin()).unwrap(),
            Some(prototypes.set_prototype),
        ),
        weak_map: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_weak_map_builtin(),
            public_builtin_metadata(js3_weak_map_builtin()).unwrap(),
            Some(prototypes.weak_map_prototype),
        ),
        weak_set: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_weak_set_builtin(),
            public_builtin_metadata(js3_weak_set_builtin()).unwrap(),
            Some(prototypes.weak_set_prototype),
        ),
        weak_ref: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_weak_ref_builtin(),
            public_builtin_metadata(js3_weak_ref_builtin()).unwrap(),
            Some(prototypes.weak_ref_prototype),
        ),
        finalization_registry: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_finalization_registry_builtin(),
            public_builtin_metadata(js3_finalization_registry_builtin()).unwrap(),
            Some(prototypes.finalization_registry_prototype),
        ),
        map_get: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_map_get_builtin(),
            public_builtin_metadata(js3_map_get_builtin()).unwrap(),
            None,
        ),
        map_set: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_map_set_builtin(),
            public_builtin_metadata(js3_map_set_builtin()).unwrap(),
            None,
        ),
        map_has: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_map_has_builtin(),
            public_builtin_metadata(js3_map_has_builtin()).unwrap(),
            None,
        ),
        map_delete: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_map_delete_builtin(),
            public_builtin_metadata(js3_map_delete_builtin()).unwrap(),
            None,
        ),
        map_clear: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_map_clear_builtin(),
            public_builtin_metadata(js3_map_clear_builtin()).unwrap(),
            None,
        ),
        map_entries: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_map_entries_builtin(),
            public_builtin_metadata(js3_map_entries_builtin()).unwrap(),
            None,
        ),
        map_values: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_map_values_builtin(),
            public_builtin_metadata(js3_map_values_builtin()).unwrap(),
            None,
        ),
        map_keys: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_map_keys_builtin(),
            public_builtin_metadata(js3_map_keys_builtin()).unwrap(),
            None,
        ),
        map_for_each: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_map_for_each_builtin(),
            public_builtin_metadata(js3_map_for_each_builtin()).unwrap(),
            None,
        ),
        map_size_getter: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_map_size_getter_builtin(),
            public_builtin_metadata(js3_map_size_getter_builtin()).unwrap(),
            None,
        ),
        set_add: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_set_add_builtin(),
            public_builtin_metadata(js3_set_add_builtin()).unwrap(),
            None,
        ),
        set_has: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_set_has_builtin(),
            public_builtin_metadata(js3_set_has_builtin()).unwrap(),
            None,
        ),
        set_delete: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_set_delete_builtin(),
            public_builtin_metadata(js3_set_delete_builtin()).unwrap(),
            None,
        ),
        set_clear: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_set_clear_builtin(),
            public_builtin_metadata(js3_set_clear_builtin()).unwrap(),
            None,
        ),
        set_entries: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_set_entries_builtin(),
            public_builtin_metadata(js3_set_entries_builtin()).unwrap(),
            None,
        ),
        set_values: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_set_values_builtin(),
            public_builtin_metadata(js3_set_values_builtin()).unwrap(),
            None,
        ),
        set_keys: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_set_keys_builtin(),
            public_builtin_metadata(js3_set_keys_builtin()).unwrap(),
            None,
        ),
        set_for_each: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_set_for_each_builtin(),
            public_builtin_metadata(js3_set_for_each_builtin()).unwrap(),
            None,
        ),
        set_size_getter: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_set_size_getter_builtin(),
            public_builtin_metadata(js3_set_size_getter_builtin()).unwrap(),
            None,
        ),
        weak_map_get: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_weak_map_get_builtin(),
            public_builtin_metadata(js3_weak_map_get_builtin()).unwrap(),
            None,
        ),
        weak_map_set: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_weak_map_set_builtin(),
            public_builtin_metadata(js3_weak_map_set_builtin()).unwrap(),
            None,
        ),
        weak_map_has: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_weak_map_has_builtin(),
            public_builtin_metadata(js3_weak_map_has_builtin()).unwrap(),
            None,
        ),
        weak_map_delete: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_weak_map_delete_builtin(),
            public_builtin_metadata(js3_weak_map_delete_builtin()).unwrap(),
            None,
        ),
        weak_set_add: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_weak_set_add_builtin(),
            public_builtin_metadata(js3_weak_set_add_builtin()).unwrap(),
            None,
        ),
        weak_set_has: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_weak_set_has_builtin(),
            public_builtin_metadata(js3_weak_set_has_builtin()).unwrap(),
            None,
        ),
        weak_set_delete: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_weak_set_delete_builtin(),
            public_builtin_metadata(js3_weak_set_delete_builtin()).unwrap(),
            None,
        ),
        weak_ref_deref: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_weak_ref_deref_builtin(),
            public_builtin_metadata(js3_weak_ref_deref_builtin()).unwrap(),
            None,
        ),
        finalization_registry_register: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_finalization_registry_register_builtin(),
            public_builtin_metadata(js3_finalization_registry_register_builtin()).unwrap(),
            None,
        ),
        finalization_registry_unregister: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_finalization_registry_unregister_builtin(),
            public_builtin_metadata(js3_finalization_registry_unregister_builtin()).unwrap(),
            None,
        ),
        map_prototype: prototypes.map_prototype,
        set_prototype: prototypes.set_prototype,
        weak_map_prototype: prototypes.weak_map_prototype,
        weak_set_prototype: prototypes.weak_set_prototype,
        weak_ref_prototype: prototypes.weak_ref_prototype,
        finalization_registry_prototype: prototypes.finalization_registry_prototype,
    }
}
