use super::{FamilyInstallContext, FunctionFamilyBuiltins, FunctionFamilyPrototypes};
use crate::public::{allocate_builtin_function_object, public_builtin_metadata};
use lyng_js_env::Agent;
use lyng_js_types::{
    js3_async_function_builtin, js3_async_generator_function_builtin,
    js3_async_generator_next_builtin, js3_async_generator_return_builtin,
    js3_async_generator_throw_builtin, js3_function_apply_builtin, js3_function_bind_builtin,
    js3_function_builtin, js3_function_call_builtin, js3_function_symbol_has_instance_builtin,
    js3_function_to_string_builtin, js3_generator_function_builtin, js3_generator_next_builtin,
    js3_generator_return_builtin, js3_generator_throw_builtin,
};

#[allow(clippy::too_many_lines)]
pub(in crate::public) fn install_function_family(
    agent: &mut Agent,
    cx: FamilyInstallContext,
    prototypes: FunctionFamilyPrototypes,
) -> FunctionFamilyBuiltins {
    FunctionFamilyBuiltins {
        function: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_function_builtin(),
            public_builtin_metadata(js3_function_builtin()).unwrap(),
            Some(cx.function_prototype),
        ),
        function_prototype: cx.function_prototype,
        function_call: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_function_call_builtin(),
            public_builtin_metadata(js3_function_call_builtin()).unwrap(),
            None,
        ),
        function_apply: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_function_apply_builtin(),
            public_builtin_metadata(js3_function_apply_builtin()).unwrap(),
            None,
        ),
        function_bind: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_function_bind_builtin(),
            public_builtin_metadata(js3_function_bind_builtin()).unwrap(),
            None,
        ),
        function_to_string: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_function_to_string_builtin(),
            public_builtin_metadata(js3_function_to_string_builtin()).unwrap(),
            None,
        ),
        function_symbol_has_instance: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_function_symbol_has_instance_builtin(),
            public_builtin_metadata(js3_function_symbol_has_instance_builtin()).unwrap(),
            None,
        ),
        async_function: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_async_function_builtin(),
            public_builtin_metadata(js3_async_function_builtin()).unwrap(),
            Some(prototypes.async_function_prototype),
        ),
        async_function_prototype: prototypes.async_function_prototype,
        async_generator_function: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_async_generator_function_builtin(),
            public_builtin_metadata(js3_async_generator_function_builtin()).unwrap(),
            Some(prototypes.async_generator_function_prototype),
        ),
        async_generator_function_prototype: prototypes.async_generator_function_prototype,
        async_generator_prototype: prototypes.async_generator_prototype,
        async_generator_next: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_async_generator_next_builtin(),
            public_builtin_metadata(js3_async_generator_next_builtin()).unwrap(),
            None,
        ),
        async_generator_return: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_async_generator_return_builtin(),
            public_builtin_metadata(js3_async_generator_return_builtin()).unwrap(),
            None,
        ),
        async_generator_throw: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_async_generator_throw_builtin(),
            public_builtin_metadata(js3_async_generator_throw_builtin()).unwrap(),
            None,
        ),
        generator_function: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_generator_function_builtin(),
            public_builtin_metadata(js3_generator_function_builtin()).unwrap(),
            Some(prototypes.generator_function_prototype),
        ),
        generator_function_prototype: prototypes.generator_function_prototype,
        generator_prototype: prototypes.generator_prototype,
        generator_next: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_generator_next_builtin(),
            public_builtin_metadata(js3_generator_next_builtin()).unwrap(),
            None,
        ),
        generator_return: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_generator_return_builtin(),
            public_builtin_metadata(js3_generator_return_builtin()).unwrap(),
            None,
        ),
        generator_throw: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_generator_throw_builtin(),
            public_builtin_metadata(js3_generator_throw_builtin()).unwrap(),
            None,
        ),
    }
}
