use super::{FamilyInstallContext, ObjectFamilyBuiltins};
use crate::public::{allocate_builtin_function_object, public_builtin_metadata};
use lyng_js_env::Agent;
use lyng_js_types::{
    js3_object_assign_builtin, js3_object_builtin, js3_object_create_builtin,
    js3_object_define_getter_builtin, js3_object_define_properties_builtin,
    js3_object_define_property_builtin, js3_object_define_setter_builtin,
    js3_object_entries_builtin, js3_object_freeze_builtin, js3_object_from_entries_builtin,
    js3_object_get_own_property_descriptor_builtin,
    js3_object_get_own_property_descriptors_builtin, js3_object_get_own_property_names_builtin,
    js3_object_get_own_property_symbols_builtin, js3_object_get_prototype_of_builtin,
    js3_object_group_by_builtin, js3_object_has_own_builtin, js3_object_has_own_property_builtin,
    js3_object_is_builtin, js3_object_is_extensible_builtin, js3_object_is_frozen_builtin,
    js3_object_is_prototype_of_builtin, js3_object_is_sealed_builtin, js3_object_keys_builtin,
    js3_object_lookup_getter_builtin, js3_object_lookup_setter_builtin,
    js3_object_prevent_extensions_builtin, js3_object_property_is_enumerable_builtin,
    js3_object_proto_getter_builtin, js3_object_proto_setter_builtin, js3_object_seal_builtin,
    js3_object_set_prototype_of_builtin, js3_object_to_locale_string_builtin,
    js3_object_to_string_builtin, js3_object_value_of_builtin, js3_object_values_builtin,
};

#[allow(clippy::too_many_lines)]
pub(in crate::public) fn install_object_family(
    agent: &mut Agent,
    cx: FamilyInstallContext,
) -> ObjectFamilyBuiltins {
    ObjectFamilyBuiltins {
        object: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_builtin(),
            public_builtin_metadata(js3_object_builtin()).unwrap(),
            Some(cx.object_prototype),
        ),
        object_prototype: cx.object_prototype,
        object_create: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_create_builtin(),
            public_builtin_metadata(js3_object_create_builtin()).unwrap(),
            None,
        ),
        object_get_prototype_of: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_get_prototype_of_builtin(),
            public_builtin_metadata(js3_object_get_prototype_of_builtin()).unwrap(),
            None,
        ),
        object_set_prototype_of: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_set_prototype_of_builtin(),
            public_builtin_metadata(js3_object_set_prototype_of_builtin()).unwrap(),
            None,
        ),
        object_get_own_property_descriptor: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_get_own_property_descriptor_builtin(),
            public_builtin_metadata(js3_object_get_own_property_descriptor_builtin()).unwrap(),
            None,
        ),
        object_get_own_property_descriptors: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_get_own_property_descriptors_builtin(),
            public_builtin_metadata(js3_object_get_own_property_descriptors_builtin()).unwrap(),
            None,
        ),
        object_get_own_property_names: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_get_own_property_names_builtin(),
            public_builtin_metadata(js3_object_get_own_property_names_builtin()).unwrap(),
            None,
        ),
        object_get_own_property_symbols: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_get_own_property_symbols_builtin(),
            public_builtin_metadata(js3_object_get_own_property_symbols_builtin()).unwrap(),
            None,
        ),
        object_define_properties: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_define_properties_builtin(),
            public_builtin_metadata(js3_object_define_properties_builtin()).unwrap(),
            None,
        ),
        object_define_property: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_define_property_builtin(),
            public_builtin_metadata(js3_object_define_property_builtin()).unwrap(),
            None,
        ),
        object_assign: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_assign_builtin(),
            public_builtin_metadata(js3_object_assign_builtin()).unwrap(),
            None,
        ),
        object_from_entries: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_from_entries_builtin(),
            public_builtin_metadata(js3_object_from_entries_builtin()).unwrap(),
            None,
        ),
        object_group_by: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_group_by_builtin(),
            public_builtin_metadata(js3_object_group_by_builtin()).unwrap(),
            None,
        ),
        object_prevent_extensions: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_prevent_extensions_builtin(),
            public_builtin_metadata(js3_object_prevent_extensions_builtin()).unwrap(),
            None,
        ),
        object_is_extensible: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_is_extensible_builtin(),
            public_builtin_metadata(js3_object_is_extensible_builtin()).unwrap(),
            None,
        ),
        object_is: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_is_builtin(),
            public_builtin_metadata(js3_object_is_builtin()).unwrap(),
            None,
        ),
        object_seal: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_seal_builtin(),
            public_builtin_metadata(js3_object_seal_builtin()).unwrap(),
            None,
        ),
        object_freeze: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_freeze_builtin(),
            public_builtin_metadata(js3_object_freeze_builtin()).unwrap(),
            None,
        ),
        object_is_sealed: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_is_sealed_builtin(),
            public_builtin_metadata(js3_object_is_sealed_builtin()).unwrap(),
            None,
        ),
        object_is_frozen: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_is_frozen_builtin(),
            public_builtin_metadata(js3_object_is_frozen_builtin()).unwrap(),
            None,
        ),
        object_to_locale_string: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_to_locale_string_builtin(),
            public_builtin_metadata(js3_object_to_locale_string_builtin()).unwrap(),
            None,
        ),
        object_to_string: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_to_string_builtin(),
            public_builtin_metadata(js3_object_to_string_builtin()).unwrap(),
            None,
        ),
        object_value_of: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_value_of_builtin(),
            public_builtin_metadata(js3_object_value_of_builtin()).unwrap(),
            None,
        ),
        object_has_own_property: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_has_own_property_builtin(),
            public_builtin_metadata(js3_object_has_own_property_builtin()).unwrap(),
            None,
        ),
        object_is_prototype_of: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_is_prototype_of_builtin(),
            public_builtin_metadata(js3_object_is_prototype_of_builtin()).unwrap(),
            None,
        ),
        object_property_is_enumerable: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_property_is_enumerable_builtin(),
            public_builtin_metadata(js3_object_property_is_enumerable_builtin()).unwrap(),
            None,
        ),
        object_define_getter: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_define_getter_builtin(),
            public_builtin_metadata(js3_object_define_getter_builtin()).unwrap(),
            None,
        ),
        object_define_setter: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_define_setter_builtin(),
            public_builtin_metadata(js3_object_define_setter_builtin()).unwrap(),
            None,
        ),
        object_lookup_getter: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_lookup_getter_builtin(),
            public_builtin_metadata(js3_object_lookup_getter_builtin()).unwrap(),
            None,
        ),
        object_lookup_setter: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_lookup_setter_builtin(),
            public_builtin_metadata(js3_object_lookup_setter_builtin()).unwrap(),
            None,
        ),
        object_proto_getter: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_proto_getter_builtin(),
            public_builtin_metadata(js3_object_proto_getter_builtin()).unwrap(),
            None,
        ),
        object_proto_setter: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_proto_setter_builtin(),
            public_builtin_metadata(js3_object_proto_setter_builtin()).unwrap(),
            None,
        ),
        object_keys: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_keys_builtin(),
            public_builtin_metadata(js3_object_keys_builtin()).unwrap(),
            None,
        ),
        object_entries: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_entries_builtin(),
            public_builtin_metadata(js3_object_entries_builtin()).unwrap(),
            None,
        ),
        object_values: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_values_builtin(),
            public_builtin_metadata(js3_object_values_builtin()).unwrap(),
            None,
        ),
        object_has_own: allocate_builtin_function_object(
            agent,
            cx.realm,
            cx.global_env,
            cx.root_shape,
            cx.function_prototype,
            cx.object_prototype,
            js3_object_has_own_builtin(),
            public_builtin_metadata(js3_object_has_own_builtin()).unwrap(),
            None,
        ),
    }
}
