//! Dispatch, branches, and slow-path bridge fragments for AArch64.
//!
//! This module is the most-used backend file: every fast-path handler
//! ends in [`dispatch!`], every slow-path handler ends in
//! [`dispatch_after_slow!`], and the prefix opcodes (`op_wide` /
//! `op_extra_wide`) use [`dispatch_prefixed!`].
//!
//! ## Pinned-register convention (from `reg_convention.rs`)
//!
//! | Reg  | Pin                                  |
//! | ---- | ------------------------------------ |
//! | x19  | PC (`*const u8`)                     |
//! | x20  | REGS (`*mut Value`)                  |
//! | x21  | FV (`*mut FeedbackEntry`)            |
//! | x22  | VM (`*mut Vm`)                       |
//! | x23  | TABLE (`*const DslHandler`)          |
//! | x24  | STATE (`*mut LlIntState`)            |
//!
//! ## Bindings expected from the proc-macro lowerer
//!
//! Each macro emits a fragment with `{...}` placeholders that the
//! enclosing `naked_asm!(...)` must resolve. Bindings used here:
//!
//! - `{length}`     — encoded length of the current handler.
//! - `{shim}`       — `sym op_xxx_slow_rs` (Rust slow-path symbol).
//! - `{exit}`       — `sym crate::dsl::entry::_interpreter_exit`.
//! - `{state_pc}`   — `const LLINT_STATE_FRAME_PC_OFFSET`.
//! - `{state_pb}`   — `const LLINT_STATE_FRAME_PB_BASE`.
//! - `{state_regs}` — `const LLINT_STATE_FRAME_REGS_BASE`.
//! - `{state_fv}`   — `const LLINT_STATE_FRAME_FV_BASE`.
//! - `{state_prefix}` — `const LLINT_STATE_PREFIX`.
//!
//! The lowerer in `lyng-js-vm-dsl::lower` is responsible for emitting
//! the corresponding `name = const ...` / `name = sym ...` lines
//! inside the `naked_asm!`. Backend macros only emit the placeholders.

// ===========================================================================
// Tail-jump dispatch.
// ===========================================================================

/// End-of-handler dispatch with auto-advance by `{length}` bytes (the
/// handler's encoded length, supplied by the proc-macro at lower time).
///
/// Compiles to 4 instructions:
/// ```text
///     add  x19, x19, {length}    ; advance PC
///     ldrb w8, [x19]             ; load next opcode byte
///     ldr  x9, [x23, x8, lsl #3] ; look up handler addr
///     br   x9                    ; tail-jump
/// ```
#[macro_export]
macro_rules! dispatch {
    () => {
        concat!(
            "add    x19, x19, {length}\n",
            "ldrb   w8, [x19]\n",
            "ldr    x9, [x23, x8, lsl #3]\n",
            "br     x9\n",
        )
    };
    (advance = $n:literal) => {
        concat!(
            "add    x19, x19, #", stringify!($n), "\n",
            "ldrb   w8, [x19]\n",
            "ldr    x9, [x23, x8, lsl #3]\n",
            "br     x9\n",
        )
    };
}

// ===========================================================================
// Slow-path bridge.
// ===========================================================================

/// Call into a Rust slow-path shim. The shim signature is
/// `extern "C" fn(state: *mut LlIntState, op0: u32, ...) -> u64`.
///
/// **Pre-call refresh** (asm-visible discipline per design §7):
///
/// 1. Compute `pc_offset = PC - pb_base` and store at
///    `state.frame_pc_offset` so the shim can inspect the bytecode
///    cursor.
/// 2. Move `STATE` to a0 (`x0`).
/// 3. Move each operand reg into the corresponding argument slot
///    (a1..a5 = `w1..w5`). The variadic `args = [...]` list expands
///    one `mov` per operand — generated by the proc-macro lowerer at
///    lower time, *not* here, because the operand list is dynamic.
/// 4. `bl {shim}`.
///
/// Bindings: `{shim}`, `{state_pb}`, `{state_pc}`.
#[macro_export]
macro_rules! call_slow {
    ($shim:ident, args = [$($arg:ident),*]) => {
        concat!(
            // Pre-call: state.frame_pc_offset := PC - pb_base
            "ldr    x9, [x24, {state_pb}]\n",
            "sub    x10, x19, x9\n",
            "str    w10, [x24, {state_pc}]\n",
            // a0 := STATE
            "mov    x0, x24\n",
            // Per-operand mov-into-arg-slot. The proc-macro lowerer
            // replaces `{arg_n}` placeholders at lower time with the
            // correct destination W-register index (w1, w2, ...).
            $("mov    w{arg_slot}, w", stringify!($arg), "\n",)*
            // Call shim. The {shim} placeholder is resolved to a
            // `sym op_xxx_slow_rs` by the lowerer's binding list.
            "bl     {shim}\n",
        )
    };
}

/// Post-`call_slow!` dispatch.
///
/// The shim returns a tagged u64:
///
/// - `0x0` (Continue, low 32 = new pc_offset) → reload `PC` and
///   tail-jump to the next handler.
/// - `0x1` (Refresh, low 32 = new pc_offset) → reload PC, REGS, FV
///   from `state.frame_*` (a frame switch happened) and tail-jump.
/// - `0x2` (Exit) → branch to `{exit}` symbol.
///
/// Bindings: `{exit}`, `{state_pb}`, `{state_pc}`, `{state_regs}`,
/// `{state_fv}`.
#[macro_export]
macro_rules! dispatch_after_slow {
    () => {
        concat!(
            // Common case first: tag == Continue (0).
            "cbnz   x0, .Lunusual\n",
            // Continue path: PC = pb_base + new_offset (low 32 of x1).
            "ldr    x9, [x24, {state_pb}]\n",
            "add    x19, x9, x1\n",
            "ldrb   w8, [x19]\n",
            "ldr    x10, [x23, x8, lsl #3]\n",
            "br     x10\n",
            ".Lunusual:\n",
            "cmp    x0, #2\n",
            "b.eq   .Lexit\n",
            // Refresh path: reload PC / REGS / FV from state.frame_*.
            "ldr    w11, [x24, {state_pc}]\n",
            "ldr    x9,  [x24, {state_pb}]\n",
            "add    x19, x9, x11\n",
            "ldr    x20, [x24, {state_regs}]\n",
            "ldr    x21, [x24, {state_fv}]\n",
            "ldrb   w8,  [x19]\n",
            "ldr    x10, [x23, x8, lsl #3]\n",
            "br     x10\n",
            ".Lexit:\n",
            "b      {exit}\n",
        )
    };
}

// ===========================================================================
// Branches.
// ===========================================================================

/// Branch to `$label` if `$reg` is zero (`cbz xR, label`).
#[macro_export]
macro_rules! branch_zero {
    ($reg:ident, $label:tt) => {
        concat!(
            "cbz    x", stringify!($reg), ", ", stringify!($label), "\n",
        )
    };
}

/// Branch to `$label` if `$reg` is non-zero (`cbnz xR, label`).
#[macro_export]
macro_rules! branch_nonzero {
    ($reg:ident, $label:tt) => {
        concat!(
            "cbnz   x", stringify!($reg), ", ", stringify!($label), "\n",
        )
    };
}

/// Unconditional branch to a local label.
#[macro_export]
macro_rules! branch {
    ($label:tt) => {
        concat!("b      ", stringify!($label), "\n",)
    };
}

/// Emit a local label inside the handler body.
#[macro_export]
macro_rules! label {
    ($label:tt) => {
        concat!(stringify!($label), ":\n",)
    };
}

// ===========================================================================
// Prefix dispatch (op_wide / op_extra_wide).
// ===========================================================================

/// Prefix-opcode handler body. Stashes the prefix kind in
/// `state.prefix`, advances PC by 1, and tail-jumps to the next
/// opcode's handler. Rejects a doubled prefix (e.g. `wide wide`) by
/// dropping into a slow-path shim.
///
/// `$kind` is the prefix discriminator (1 for `wide`, 2 for
/// `extra_wide`) — a literal u8.
///
/// **TODO (Batch 7):** `.Ldouble_prefix` currently hits `brk #0` because
/// `op_double_prefix_slow_rs` doesn't exist yet. When the `op_wide` /
/// `op_extra_wide` ports land in Batch 7, replace the `brk #0` with a
/// `call_slow!(op_double_prefix_slow_rs, args = [])` + a proper exit
/// path.
///
/// Bindings: `{state_prefix}`.
#[macro_export]
macro_rules! dispatch_prefixed {
    (kind = $kind:literal) => {
        concat!(
            // Reject doubled prefix.
            "ldrb   w9, [x24, {state_prefix}]\n",
            "cbnz   w9, .Ldouble_prefix\n",
            // Stash prefix discriminator.
            "mov    w9, #", stringify!($kind), "\n",
            "strb   w9, [x24, {state_prefix}]\n",
            // Advance PC past the prefix byte and dispatch.
            "add    x19, x19, #1\n",
            "ldrb   w8, [x19]\n",
            "ldr    x10, [x23, x8, lsl #3]\n",
            "br     x10\n",
            ".Ldouble_prefix:\n",
            // TODO: call op_double_prefix_slow_rs once Batch 7 lands.
            "brk    #0\n",
        )
    };
}
