/// All 80 tokenizer states from the WHATWG HTML spec (§13.2.5).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum State {
    Data,                                     // 13.2.5.1
    RcData,                                   // 13.2.5.2
    RawText,                                  // 13.2.5.3
    ScriptData,                               // 13.2.5.4
    PlainText,                                // 13.2.5.5
    TagOpen,                                  // 13.2.5.6
    EndTagOpen,                               // 13.2.5.7
    TagName,                                  // 13.2.5.8
    RcDataLessThanSign,                       // 13.2.5.9
    RcDataEndTagOpen,                         // 13.2.5.10
    RcDataEndTagName,                         // 13.2.5.11
    RawTextLessThanSign,                      // 13.2.5.12
    RawTextEndTagOpen,                        // 13.2.5.13
    RawTextEndTagName,                        // 13.2.5.14
    ScriptDataLessThanSign,                   // 13.2.5.15
    ScriptDataEndTagOpen,                     // 13.2.5.16
    ScriptDataEndTagName,                     // 13.2.5.17
    ScriptDataEscapeStart,                    // 13.2.5.18
    ScriptDataEscapeStartDash,                // 13.2.5.19
    ScriptDataEscaped,                        // 13.2.5.20
    ScriptDataEscapedDash,                    // 13.2.5.21
    ScriptDataEscapedDashDash,                // 13.2.5.22
    ScriptDataEscapedLessThanSign,            // 13.2.5.23
    ScriptDataEscapedEndTagOpen,              // 13.2.5.24
    ScriptDataEscapedEndTagName,              // 13.2.5.25
    ScriptDataDoubleEscapeStart,              // 13.2.5.26
    ScriptDataDoubleEscaped,                  // 13.2.5.27
    ScriptDataDoubleEscapedDash,              // 13.2.5.28
    ScriptDataDoubleEscapedDashDash,          // 13.2.5.29
    ScriptDataDoubleEscapedLessThanSign,      // 13.2.5.30
    ScriptDataDoubleEscapeEnd,                // 13.2.5.31
    BeforeAttributeName,                      // 13.2.5.32
    AttributeName,                            // 13.2.5.33
    AfterAttributeName,                       // 13.2.5.34
    BeforeAttributeValue,                     // 13.2.5.35
    AttributeValueDoubleQuoted,               // 13.2.5.36
    AttributeValueSingleQuoted,               // 13.2.5.37
    AttributeValueUnquoted,                   // 13.2.5.38
    AfterAttributeValueQuoted,                // 13.2.5.39
    SelfClosingStartTag,                      // 13.2.5.40
    BogusComment,                             // 13.2.5.41
    MarkupDeclarationOpen,                    // 13.2.5.42
    CommentStart,                             // 13.2.5.43
    CommentStartDash,                         // 13.2.5.44
    Comment,                                  // 13.2.5.45
    CommentLessThanSign,                      // 13.2.5.46
    CommentLessThanSignBang,                  // 13.2.5.47
    CommentLessThanSignBangDash,              // 13.2.5.48
    CommentLessThanSignBangDashDash,          // 13.2.5.49
    CommentEndDash,                           // 13.2.5.50
    CommentEnd,                               // 13.2.5.51
    CommentEndBang,                           // 13.2.5.52
    Doctype,                                  // 13.2.5.53
    BeforeDoctypeName,                        // 13.2.5.54
    DoctypeName,                              // 13.2.5.55
    AfterDoctypeName,                         // 13.2.5.56
    AfterDoctypePublicKeyword,                // 13.2.5.57
    BeforeDoctypePublicIdentifier,            // 13.2.5.58
    DoctypePublicIdentifierDoubleQuoted,      // 13.2.5.59
    DoctypePublicIdentifierSingleQuoted,      // 13.2.5.60
    AfterDoctypePublicIdentifier,             // 13.2.5.61
    BetweenDoctypePublicAndSystemIdentifiers, // 13.2.5.62
    AfterDoctypeSystemKeyword,                // 13.2.5.63
    BeforeDoctypeSystemIdentifier,            // 13.2.5.64
    DoctypeSystemIdentifierDoubleQuoted,      // 13.2.5.65
    DoctypeSystemIdentifierSingleQuoted,      // 13.2.5.66
    AfterDoctypeSystemIdentifier,             // 13.2.5.67
    BogusDoctype,                             // 13.2.5.68
    CdataSection,                             // 13.2.5.69
    CdataSectionBracket,                      // 13.2.5.70
    CdataSectionEnd,                          // 13.2.5.71
    CharacterReference,                       // 13.2.5.72
    NamedCharacterReference,                  // 13.2.5.73
    AmbiguousAmpersand,                       // 13.2.5.74
    NumericCharacterReference,                // 13.2.5.75
    HexadecimalCharacterReferenceStart,       // 13.2.5.76
    DecimalCharacterReferenceStart,           // 13.2.5.77
    HexadecimalCharacterReference,            // 13.2.5.78
    DecimalCharacterReference,                // 13.2.5.79
    NumericCharacterReferenceEnd,             // 13.2.5.80
}
