[package]
name = "lyng-compiler"
version.workspace = true
edition.workspace = true

[dependencies]
lyng-common = { workspace = true }
lyng-ast = { workspace = true }
lyng-sema = { workspace = true }
lyng-env = { workspace = true }
lyng-bytecode = { workspace = true }
lyng-host = { workspace = true }
lyng-parser = { workspace = true }
lyng-types = { workspace = true }

[dev-dependencies]
