use std::collections::HashMap;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;
use std::time::Duration;

use crate::selection::ExclusionManifest;

pub(crate) const DEFAULT_FAILURE_LIMIT: usize = 200;

#[derive(Default, Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct CategoryStats {
    pub(crate) pass: u32,
    pub(crate) fail: u32,
    pub(crate) skip: u32,
    pub(crate) panic: u32,
}

impl CategoryStats {
    pub(crate) fn attempted(&self) -> u32 {
        self.pass + self.fail + self.panic
    }

    pub(crate) fn selected(&self) -> u32 {
        self.attempted() + self.skip
    }

    pub(crate) fn reported_failures(&self) -> u32 {
        self.fail
    }

    pub(crate) fn pass_rate(&self) -> f64 {
        let selected = self.selected();
        if selected == 0 {
            0.0
        } else {
            f64::from(self.pass) / f64::from(selected) * 100.0
        }
    }
}

pub(crate) struct SuiteReport<'a> {
    pub(crate) report_path: &'a str,
    pub(crate) manifest: &'a ExclusionManifest,
    pub(crate) filter: Option<&'a str>,
    pub(crate) no_skip: bool,
    pub(crate) timeout: Duration,
    pub(crate) candidate_total: usize,
    pub(crate) selected_total: usize,
    pub(crate) selected_counts: &'a HashMap<String, usize>,
    pub(crate) category_stats: &'a HashMap<String, CategoryStats>,
    pub(crate) skip_reasons: &'a HashMap<String, u32>,
    pub(crate) failures: &'a [String],
    pub(crate) elapsed: Duration,
}

struct ReportTotals {
    total_pass: u32,
    total_fail: u32,
    total_skip: u32,
    total_panic: u32,
    runnable: u32,
    excluded_from_selection: usize,
    pass_rate: f64,
}

pub(crate) fn write_report(report: &SuiteReport<'_>) {
    if let Some(parent) = Path::new(report.report_path).parent() {
        let _ = fs::create_dir_all(parent);
    }

    let totals = compute_totals(report);

    let mut out = String::new();
    write_report_header(&mut out, report);
    write_run_section(&mut out, report);
    write_summary_section(&mut out, report, &totals);
    write_category_section(&mut out, report);
    write_skip_section(&mut out, report);
    write_manifest_section(&mut out, report);
    write_failure_section(&mut out, report);
    write_notes_section(&mut out, report);

    if let Err(error) = fs::write(report.report_path, out) {
        eprintln!("Failed to write report to {}: {error}", report.report_path);
    } else {
        eprintln!("Report written to {}", report.report_path);
    }
}

pub(crate) fn format_pass_rate(rate: f64) -> String {
    format!("{rate:.2}")
}

fn compute_totals(report: &SuiteReport<'_>) -> ReportTotals {
    let total_pass = report
        .category_stats
        .values()
        .map(|stats| stats.pass)
        .sum::<u32>();
    let total_fail = report
        .category_stats
        .values()
        .map(CategoryStats::reported_failures)
        .sum::<u32>();
    let total_skip = report
        .category_stats
        .values()
        .map(|stats| stats.skip)
        .sum::<u32>();
    let total_panic = report
        .category_stats
        .values()
        .map(|stats| stats.panic)
        .sum::<u32>();
    let runnable = report
        .category_stats
        .values()
        .map(CategoryStats::attempted)
        .sum::<u32>();
    let selected = total_pass + total_fail + total_panic + total_skip;
    let pass_rate = if selected == 0 {
        0.0
    } else {
        f64::from(total_pass) / f64::from(selected) * 100.0
    };

    ReportTotals {
        total_pass,
        total_fail,
        total_skip,
        total_panic,
        runnable,
        excluded_from_selection: report.candidate_total.saturating_sub(report.selected_total),
        pass_rate,
    }
}

fn write_report_header(out: &mut String, report: &SuiteReport<'_>) {
    let _ = writeln!(out, "# Lyng JS Whole-Suite Test262 Report");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "This report is generated by `cargo run --release -p lyng-js-test262 -- --report {}`.",
        report.report_path
    );
    let _ = writeln!(
        out,
        "It executes the current Lyng JS runtime harness across the Test262 corpus with path-based filtering only."
    );
    let _ = writeln!(out);
}

fn write_run_section(out: &mut String, report: &SuiteReport<'_>) {
    let filter_label = report.filter.map_or_else(
        || "`whole corpus`".to_string(),
        |value| format!("`{value}`"),
    );
    let _ = writeln!(out, "## Run");
    let _ = writeln!(out);
    let _ = writeln!(out, "- Filter: {filter_label}");
    let _ = writeln!(
        out,
        "- Skip mode: {}",
        if report.no_skip {
            "`disabled via --no-skip`"
        } else {
            "`default heuristics`"
        }
    );
    let _ = writeln!(
        out,
        "- Per-test timeout: `{:.1}s`",
        report.timeout.as_secs_f64()
    );
    let _ = writeln!(out, "- Exclusion manifest: `{}`", report.manifest.path);
    let _ = writeln!(
        out,
        "- Category breakdown groups tests by the first path component under `testdata/test262/test/`."
    );
    let _ = writeln!(
        out,
        "- Skipped tests are reported separately and still count against the selected-test pass rate."
    );
    let _ = writeln!(out);
}

fn write_summary_section(out: &mut String, report: &SuiteReport<'_>, totals: &ReportTotals) {
    let _ = writeln!(out, "## Summary");
    let _ = writeln!(out);
    let _ = writeln!(out, "| Metric | Count |");
    let _ = writeln!(out, "| --- | ---: |");
    let _ = writeln!(out, "| Candidate tests | `{}` |", report.candidate_total);
    let _ = writeln!(
        out,
        "| Excluded from selection | `{}` |",
        totals.excluded_from_selection
    );
    let _ = writeln!(out, "| Selected tests | `{}` |", report.selected_total);
    let _ = writeln!(out, "| Runnable | `{}` |", totals.runnable);
    let _ = writeln!(out, "| Passed | `{}` |", totals.total_pass);
    let _ = writeln!(out, "| Failed | `{}` |", totals.total_fail);
    let _ = writeln!(out, "| Panicked | `{}` |", totals.total_panic);
    let _ = writeln!(out, "| Skipped | `{}` |", totals.total_skip);
    let _ = writeln!(
        out,
        "| Pass rate (selected) | `{}%` |",
        format_pass_rate(totals.pass_rate)
    );
    let _ = writeln!(out, "| Time | `{:.1}s` |", report.elapsed.as_secs_f64());
    let _ = writeln!(out);
}

fn write_category_section(out: &mut String, report: &SuiteReport<'_>) {
    let _ = writeln!(out, "## Category Breakdown");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "| Category | Selected | Runnable | Pass | Fail | Skip | Panic | Rate |"
    );
    let _ = writeln!(
        out,
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |"
    );
    let mut category_rows: Vec<_> = report.category_stats.iter().collect();
    category_rows.sort_by(|left, right| left.0.cmp(right.0));
    for (category, stats) in category_rows {
        let selected = report.selected_counts.get(category).copied().unwrap_or(0);
        let _ = writeln!(
            out,
            "| `{}` | `{}` | `{}` | `{}` | `{}` | `{}` | `{}` | `{}%` |",
            category,
            selected,
            stats.attempted(),
            stats.pass,
            stats.reported_failures(),
            stats.skip,
            stats.panic,
            format_pass_rate(stats.pass_rate())
        );
    }
    let _ = writeln!(out);
}

fn write_skip_section(out: &mut String, report: &SuiteReport<'_>) {
    let _ = writeln!(out, "## Top Skip Reasons");
    let _ = writeln!(out);
    if report.skip_reasons.is_empty() {
        let _ = writeln!(out, "No skips recorded.");
    } else {
        let _ = writeln!(out, "| Reason | Count |");
        let _ = writeln!(out, "| --- | ---: |");
        let mut reason_rows: Vec<_> = report.skip_reasons.iter().collect();
        reason_rows.sort_by(|left, right| right.1.cmp(left.1).then_with(|| left.0.cmp(right.0)));
        for (reason, count) in reason_rows {
            let _ = writeln!(out, "| {reason} | `{count}` |");
        }
    }
    let _ = writeln!(out);
}

fn write_manifest_section(out: &mut String, report: &SuiteReport<'_>) {
    let _ = writeln!(out, "## Checked-in Manifest Rules");
    let _ = writeln!(out);
    if report.manifest.rules.is_empty() {
        let _ = writeln!(out, "No manifest rules active.");
    } else {
        let _ = writeln!(out, "| Kind | Pattern | Reason |");
        let _ = writeln!(out, "| --- | --- | --- |");
        for rule in &report.manifest.rules {
            let _ = writeln!(
                out,
                "| `{}` | `{}` | {} |",
                rule.kind.as_str(),
                rule.pattern,
                rule.reason
            );
        }
    }
    let _ = writeln!(out);
}

fn write_failure_section(out: &mut String, report: &SuiteReport<'_>) {
    let _ = writeln!(out, "## Failure Sample");
    let _ = writeln!(out);
    if report.failures.is_empty() {
        let _ = writeln!(out, "No failures recorded.");
    } else {
        for (index, failure) in report
            .failures
            .iter()
            .take(DEFAULT_FAILURE_LIMIT)
            .enumerate()
        {
            let _ = writeln!(out, "{}. {}", index + 1, failure);
        }
    }
    let _ = writeln!(out);
}

fn write_notes_section(out: &mut String, report: &SuiteReport<'_>) {
    let _ = writeln!(out, "## Notes");
    let _ = writeln!(out);
    if report.no_skip {
        let _ = writeln!(
            out,
            "- `--no-skip` was enabled for this run, so manifest exclusions, explicit path skips, and metadata/capability skips were all bypassed."
        );
    } else {
        let _ = writeln!(
            out,
            "- The checked-in exclusion manifest remains intentionally narrow. Missing engine work stays visible here as skips or failures instead of being hidden in the manifest."
        );
    }
    let _ = writeln!(
        out,
        "- Tests carrying `Error.isError` remain excluded from selection because they are outside the core ECMA-262 runner surface tracked by this tool."
    );
}

#[cfg(test)]
mod tests {
    use std::collections::HashMap;
    use std::fs;
    use std::time::{Duration, SystemTime, UNIX_EPOCH};

    use crate::selection::ExclusionManifest;

    use super::{format_pass_rate, write_report, CategoryStats, SuiteReport};

    #[test]
    fn pass_rate_counts_skips_as_non_passing_selected_tests() {
        let stats = CategoryStats {
            pass: 38_267,
            fail: 16,
            skip: 14_842,
            panic: 0,
        };

        assert_eq!(stats.attempted(), 38_283);
        assert_eq!(stats.selected(), 53_125);
        assert_eq!(stats.reported_failures(), 16);
        assert_eq!(format_pass_rate(stats.pass_rate()), "72.03");
    }

    #[test]
    fn report_documents_top_level_grouping_and_lists_skips_separately() {
        let mut selected_counts = HashMap::new();
        selected_counts.insert("built-ins".to_string(), 2);

        let mut category_stats = HashMap::new();
        category_stats.insert(
            "built-ins".to_string(),
            CategoryStats {
                pass: 1,
                fail: 0,
                skip: 1,
                panic: 0,
            },
        );

        let skip_reasons = HashMap::from([("unsupported feature".to_string(), 1)]);
        let failures = Vec::new();
        let manifest = ExclusionManifest {
            path: "reports/js/lyng-js/test262-exclusions.txt".to_string(),
            rules: Vec::new(),
        };
        let unique = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system clock should be after unix epoch")
            .as_nanos();
        let report_path = std::env::temp_dir().join(format!(
            "lyng-js-test262-report-{}-{unique}.md",
            std::process::id()
        ));
        let report_path_string = report_path.display().to_string();

        write_report(&SuiteReport {
            report_path: &report_path_string,
            manifest: &manifest,
            filter: None,
            no_skip: false,
            timeout: Duration::from_secs(1),
            candidate_total: 2,
            selected_total: 2,
            selected_counts: &selected_counts,
            category_stats: &category_stats,
            skip_reasons: &skip_reasons,
            failures: &failures,
            elapsed: Duration::from_secs(2),
        });

        let output = fs::read_to_string(&report_path).expect("report should be readable");
        let _ = fs::remove_file(&report_path);

        assert!(output.contains("first path component under `testdata/test262/test/`"));
        assert!(output.contains("| Failed | `0` |"));
        assert!(output.contains("| Skipped | `1` |"));
        assert!(output.contains("| Pass rate (selected) | `50.00%` |"));
    }
}
