//! Entry shim and exit shim per design §5 / §6.
//!
//! The entry shim ([`run_via_dsl`]) builds an [`LlIntRustContext`] and
//! a stack-local [`LlIntState`], then jumps into the asm trampoline.
//! The trampoline runs the DSL handler chain until a cold stub writes
//! `rust_ctx.exit` and the chain unwinds back to [`_interpreter_exit`].
//!
//! For DSL-0b Batch 2 the trampoline + exit shim are stubs (single
//! `ret`), and `run_via_dsl` is not wired into `Vm::run`. Calling it at
//! runtime is currently UB — there's no real handler chain. The
//! symbols exist so backend code and the proc-macro can link against
//! them. Batch 4 fills in the asm body; C1 flips dispatch.

use std::sync::Arc;

use lyng_js_env::Agent;
use lyng_js_host::HostHooks;
use lyng_js_objects::NativeFunctionRegistry;
use lyng_js_types::Value;

use crate::dsl::feedback_flat::FeedbackEntry;
use crate::dsl::llint_state::{
    ExitKind, LlIntExitSlot, LlIntRustContext, LlIntRustContextOpaque, LlIntState,
};
use crate::error::{VmError, VmResult};
use crate::vm::install::InstalledFunction;
use crate::{FrameRecord, Vm};

/// New entry point used after DSL-0c flips dispatch.
///
/// During DSL-0b this is callable but not the default — `Vm::run`
/// continues to route through the α trampoline. Task C1 swaps the
/// route. Calling it at runtime in DSL-0b is currently UB because
/// `run_dsl_trampoline` is a single-`ret` stub; the symbol exists so
/// the proc-macro and backend code can link.
#[allow(dead_code)]
pub(crate) fn run_via_dsl(
    vm: &mut Vm,
    agent: &mut Agent,
    host: &dyn HostHooks,
    registry: &mut dyn NativeFunctionRegistry,
    installed: Arc<InstalledFunction>,
    frame: FrameRecord,
) -> VmResult<Value> {
    let frame_depth = vm.frames().len();
    let pb_base = installed.function().instruction_bytes().as_ptr();
    let frame_pc_offset = frame.instruction_offset();

    let mut rust_ctx = LlIntRustContext {
        vm,
        agent,
        host,
        registry,
        installed,
        frame,
        frame_depth,
        exit: LlIntExitSlot::default(),
    };

    // frame_regs_base / frame_fv_base are placeholder null pointers in
    // DSL-0b Batch 2. Batch 3 (Task B16) wires them to live FV /
    // register-window accessors. Until then, the asm trampoline is a
    // stub and never dereferences them.
    let mut state = LlIntState {
        frame_pc_offset,
        _pad1: 0,
        frame_pb_base: pb_base,
        frame_regs_base: core::ptr::null_mut::<Value>(),
        frame_fv_base: core::ptr::null_mut::<FeedbackEntry>(),
        frame_depth: frame_depth as u32,
        frame_check_epoch: 0,
        rust_context: (&mut rust_ctx) as *mut LlIntRustContext<'_>
            as *mut LlIntRustContextOpaque,
        prefix: 0,
        _pad2: [0; 7],
    };

    // SAFETY: `state` is a valid mutable pointer to a stack-local
    // LlIntState; the asm trampoline only reads through it on the
    // current thread for the duration of this call.
    unsafe { run_dsl_trampoline(&mut state as *mut LlIntState) };

    match rust_ctx.exit.kind {
        ExitKind::Done => Ok(rust_ctx.exit.done_value),
        ExitKind::Error => Err(*rust_ctx.exit.error.take().unwrap()),
        ExitKind::None => Err(VmError::TrampolineExitedWithoutSetting),
    }
}

/// Asm-side trampoline entry. Loads pinned registers + tail-jumps to
/// the first handler. The handler chain runs until `_interpreter_exit`
/// is hit.
///
/// In DSL-0b Batch 2 the body is a single `ret` stub. Batch 4 fills
/// the body in using the AArch64 backend macros once the handler chain
/// exists. The stub means `run_via_dsl` is currently UB at runtime —
/// it returns with `rust_ctx.exit.kind == None` and surfaces as
/// `VmError::TrampolineExitedWithoutSetting`. No caller exists yet.
#[unsafe(naked)]
pub unsafe extern "C" fn run_dsl_trampoline(_state: *mut LlIntState) {
    // x0 = state. The full version sets up pinned regs from state.frame_*
    // fields, loads VM/TABLE, then tail-jumps to the first handler.
    // Stub: just return; rust_ctx.exit.kind stays None and run_via_dsl
    // surfaces TrampolineExitedWithoutSetting.
    core::arch::naked_asm!("ret");
}

/// `_interpreter_exit` is the symbolic target the slow-path bridge
/// uses to escape the trampoline. The asm `b {exit}` branches here;
/// the function reads `rust_context.exit` and returns to the caller of
/// `run_via_dsl` via a normal Rust return.
///
/// `run_dsl_trampoline` sets up a normal stack frame, so
/// `_interpreter_exit` can be a normal `extern "C"` that pops back to
/// `run_via_dsl`. Empty body = single `ret` generated by rustc.
#[unsafe(no_mangle)]
pub extern "C" fn _interpreter_exit() {
    // Intentionally empty.
}
