[package]
name = "lyng-test262"
version.workspace = true
edition.workspace = true

[[bin]]
name = "lyng-test262"
path = "src/main.rs"

[dependencies]
lyng-builtins = { workspace = true }
lyng-bytecode = { workspace = true }
lyng-common = { workspace = true }
lyng-compiler = { workspace = true }
lyng-env = { workspace = true }
lyng-host = { workspace = true }
lyng-ops = { workspace = true }
lyng-parser = { workspace = true }
lyng-sema = { workspace = true }
lyng-test262-harness = { workspace = true }
lyng-types = { workspace = true }
lyng-vm = { workspace = true }
serde_json = "1"
